# Snakefile for step
# Define rules local to this module

rule DiffAbundance:
    input:
        norm_counts_tab = "<results>/ASV_norm_counts.tsv",
        distances_matrix = "<results>/ASVs_euclidean_distance.tsv"
    output:
        "<results>/diff_abundance_report.txt"
    log:
        notebook="logs/diff_abundance_notebook.r.ipynb"
    notebook: 
        "notebooks/diff_abundance.r.ipynb"