pathvars:
  data_initial: 'data/initial'
  data_raw: 'data/raw'
  samples: 'data/raw/fastq'
  samples_filter: 'data/raw/fastq/filtered'
  temp: 'data/temp'
  results: 'results'
  reports: 'results/reports'
  figures: 'results/figures'
samples_meta: "data/initial/all_meta.csv"
trimming:
  trunc_len_f: 230
  trunc_len_r: 230
  max_ee_f: 2
  max_ee_r: 2