configfile: "workflow/snakemake.config.yaml"

include: "scripts/metadata_constants.smk"

include: "steps/01_load_and_trim/Snakefile"
include: "steps/02_taxa_with_dada2/Snakefile"
include: "steps/03_alpha_beta/Snakefile"

rule all:
    input:
        reads_loss_summary='<results>/reads_loss_summary.tsv',
        fa='<results>/ASVs.fa',
        counts='<results>/ASVs_counts.tsv',
        tax='<results>/ASVs_taxa.tsv',
        ab_report = '<reports>/notebooks/alpha_beta.pdf',
        pathways='<results>/picrust2/KO_metagenome_out/pred_metagenome_unstrat.tsv.gz'


