pathvars:
  data_initial: 'data/initial'
  data_raw: 'data/raw'
  samples: 'data/raw/fastq'
  samples_filter: 'data/raw/fastq/filtered'
  temp: 'data/temp'
  results: 'results'
  reports: 'results/reports'
  figures: 'results/figures'