name: 02_taxa_with_dada2
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - jupyter
  - notebook
  - r-dplyr
  - conda-forge::r-base
  - conda-forge::r-irkernel
  - conda-forge::r-tidyverse
  - conda-forge::r-rmarkdown
  - bioconda::bioconductor-dada2==1.38.0
  - bioconda::bioconductor-decipher==3.6.0
