name: load-fastq
channels:
  - conda-forge
  - bioconda
  - nodefaults
variables:
  NCBI_API_KEY: 4cf167d8d16b5558aab9dbd4d0a015e4ed09
dependencies:
  - sra-tools==3.2.1
  - bioconda::cutadapt==5.2
  - bioconda::fastqc==0.12.1
  - bioconda::multiqc==1.34
